run:
  tests: false


linters:
  disable-all: true
  enable:
   - deadcode
   - goconst
   - gofmt
   - goimports
   - govet
   - ineffassign
   - misspell
   - revive
   - staticcheck
   - structcheck
   - varcheck
   - vetshadow
