
[[override]]
  branch = "master"
  name = "github.com/mkrautz/goar"

[[override]]
  branch = "master"
  name = "github.com/smira/go-uuid"

[[override]]
  branch = "master"
  name = "github.com/smira/go-xz"

[[override]]
  name = "github.com/ugorji/go"
  version = "=1.1.4"

[[override]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  branch = "master"
  name = "golang.org/x/sys"

[[override]]
  branch = "v1"
  name = "gopkg.in/check.v1"
