#!/bin/sh -e

args="$@"
if [ -z "$args" ]; then
    cp /work/src/completion.d/aptly /usr/share/bash-completion/completions/
    cmd="bash"
else
    cmd="make $@"
fi

export PATH=$PATH:/work/src/build
export GOPATH=/work/src/.go

exec $cmd
