#!/bin/sh

usermod -u `stat -c %u /work/src` aptly >/dev/null
chown -R `stat -c %u /work/src` /var/lib/aptly

# use same /home/runner dir as in github workflow
chown -R `stat -c %u /work/src` /home/runner

cmd=$@
if [ -z "$cmd" ]; then
    cmd="bash"
fi
su aptly -c "cd /work/src; export HOME=/home/runner; export PATH=\$PATH:/work/src/build; $cmd"
