#!/bin/sh

# cleanup
rm -rf /app/tmp
rm -rf /tmp/aptly*

usermod -u `stat -c %u /app` aptly
chown -R `stat -c %u /app` /var/lib/aptly

# use same /home/runner dir as in github workflow
chown -R `stat -c %u /app` /home/runner
su - aptly -c "cd /app; export HOME=/home/runner; go mod tidy; make docker-test TEST=$@"
