#!/bin/sh

rm -rf /tmp/aptly*
rm -rf /home/test/.*
rm -rf /home/test/aptly-fixture-*

usermod -u `stat -c %u /app` aptly
chown -R `stat -c %u /app` /var/lib/aptly

mkdir -p /home/runner
chown -R `stat -c %u /app` /home/runner

su - aptly -c "cd /app; python3 -m venv system/env"
su - aptly -c "cd /app; go mod tidy; HOME=/home/runner make system-test"

rm -rf system/env
