#!/bin/sh

# cleanup
rm -rf /app/tmp
rm -rf /tmp/aptly*

usermod -u `stat -c %u /app` aptly >/dev/null
chown -R `stat -c %u /app` /var/lib/aptly

su - aptly -c "cd /app; export GOPATH=/app/.go; go mod tidy; make docker-test TEST=$@"
