#!/bin/sh

# cleanup
rm -rf /app/tmp
rm -rf /tmp/aptly*

mkdir -p /srv
usermod -u `stat -c %u /app` aptly >/dev/null
chown -R `stat -c %u /app` /var/lib/aptly /srv

su - aptly -c "cd /app; export export GOPATH=/app/.go; go mod tidy; make test"
