#!/bin/sh

# cleanup
rm -rf /app/tmp
rm -rf /tmp/aptly*

usermod -u `stat -c %u /app` aptly >/dev/null
chown -R `stat -c %u /app` /var/lib/aptly

# use same /home/runner dir as in github workflow
chown -R `stat -c %u /app` /home/runner

cmd=$@
if [ -z "$cmd" ]; then
    cmd="bash"
fi
su aptly -c "cd /app; GOPATH=/app/.go go install github.com/golangci/golangci-lint/cmd/golangci-lint@$GOLANGCI_LINT_VERSION; PATH=\$PATH:/app/.go/bin golangci-lint run"
