#!/bin/sh

while [ "$1" != "" ]; do
  case $1 in
    --version)
        /bin/cat <<'OUTPUT'
gpgv (GnuPG) 2.2.4
libgcrypt 1.8.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
OUTPUT
      ;;
    -?*)
      echo "Unknown option: $1"
      ;;
    *)
      break
  esac
  shift
done
